### ISSUE TITLE
Share views / bounding box with others

### ISSUE THREAD

**Issue by akselx** [synthicity/urbansim_explorer#7]
Can we get the bounding box for debugging data purposes? Expose current view in url.

**Comment by buckleytom** [comment]
something like: http://leafletjs.com/reference.html#latlngbounds-tobboxstring

**Comment by fscottfoti** [comment]
This is done using leaflet.hash.  Future maps will have the location in the url and you can just copy and paste a link.  One of the downsides of using static files is that this won't retroactively affect previous runs, but that's by design so these files are guaranteed to do what they do now for all eternity.
